// ---------- Style tokens ----------
// Generated from a palette so theme switching restyles the whole app
// from this one function instead of scattered hex codes in JSX.
export function getStyles(palette) {
  return {
    palette,
    app: {
      fontFamily: "'Inter', sans-serif",
      background: palette.bg,
      color: palette.text,
      height: "100vh",
      width: "100%",
      display: "flex",
      flexDirection: "column",
      position: "relative",
    },
    header: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "16px 24px",
      borderBottom: `1px solid ${palette.headerBorder}`,
      flexShrink: 0,
    },
    brand: {
      fontFamily: "'Space Grotesk', sans-serif",
      fontWeight: 700,
      fontSize: 18,
      letterSpacing: "0.02em",
    },
    tagline: {
      fontSize: 10.5,
      color: palette.textMuted,
      letterSpacing: "0.02em",
      marginTop: 1,
    },
    offlineBadge: {
      fontSize: 11,
      fontWeight: 600,
      color: palette.errorText,
      border: `1px solid ${palette.errorText}`,
      borderRadius: 6,
      padding: "2px 7px",
      letterSpacing: "0.03em",
    },
    iconButton: {
      background: "transparent",
      border: `1px solid ${palette.borderMuted}`,
      borderRadius: 8,
      width: 34,
      height: 34,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
    },
    chatArea: {
      flex: 1,
      overflowY: "auto",
      padding: "20px 24px",
      display: "flex",
      flexDirection: "column",
      gap: 4,
      maxWidth: 720,
      width: "100%",
      margin: "0 auto",
    },
    bubble: {
      maxWidth: "80%",
      padding: "11px 15px",
      fontSize: 14.5,
      lineHeight: 1.5,
      borderRadius: 14,
      whiteSpace: "pre-wrap",
    },
    assistantBubble: {
      alignSelf: "flex-start",
      background: palette.surface,
      border: `1px solid ${palette.border}`,
      borderBottomLeftRadius: 4,
      color: palette.text,
      display: "flex",
      flexDirection: "column",
      gap: 2,
    },
    userBubble: {
      alignSelf: "flex-end",
      background: palette.userBubble,
      color: palette.userText,
      borderBottomRightRadius: 4,
    },
    actionButton: {
      background: "transparent",
      border: "none",
      cursor: "pointer",
      padding: 3,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    codeBlock: {
      background: palette.bg,
      border: `1px solid ${palette.border}`,
      borderRadius: 8,
      padding: "10px 12px",
      overflowX: "auto",
      fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
      fontSize: 13,
      lineHeight: 1.5,
      margin: "6px 0",
    },
    inlineCode: {
      background: palette.bg,
      border: `1px solid ${palette.border}`,
      borderRadius: 4,
      padding: "1px 5px",
      fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
      fontSize: 13,
    },
    link: {
      color: palette.accent,
      textDecoration: "underline",
    },
    list: {
      margin: "4px 0",
      paddingLeft: 20,
      display: "flex",
      flexDirection: "column",
      gap: 2,
    },
    errorBanner: {
      alignSelf: "center",
      width: "100%",
      display: "flex",
      alignItems: "flex-start",
      gap: 8,
      background: palette.errorBg,
      border: `1px solid ${palette.errorBorder}`,
      color: palette.text,
      borderRadius: 12,
      padding: "10px 12px",
      marginTop: 4,
    },
    retryButton: {
      background: "transparent",
      border: `1px solid ${palette.errorText}`,
      color: palette.errorText,
      borderRadius: 8,
      padding: "3px 10px",
      fontSize: 12.5,
      cursor: "pointer",
      flexShrink: 0,
    },
    dismissButton: {
      background: "transparent",
      border: "none",
      color: palette.textMuted,
      cursor: "pointer",
      fontSize: 16,
      lineHeight: 1,
      padding: "0 2px",
      flexShrink: 0,
    },
    inputBarWrap: {
      padding: "12px 24px 20px",
      flexShrink: 0,
      maxWidth: 720,
      width: "100%",
      margin: "0 auto",
      boxSizing: "border-box",
    },
    inputBar: {
      width: "100%",
      display: "flex",
      alignItems: "flex-end",
      gap: 6,
      background: palette.surface,
      border: `1px solid ${palette.borderMuted}`,
      borderRadius: 16,
      padding: "8px 10px",
    },
    attachButton: {
      background: "transparent",
      border: "none",
      borderRadius: 10,
      width: 34,
      height: 34,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      flexShrink: 0,
    },
    attachmentChip: {
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      maxWidth: 220,
      background: palette.surface,
      border: `1px solid ${palette.borderMuted}`,
      borderRadius: 8,
      padding: "4px 8px",
      fontSize: 12,
      color: palette.textMuted,
      marginBottom: 6,
    },
    attachmentThumb: {
      width: 20,
      height: 20,
      borderRadius: 4,
      objectFit: "cover",
      flexShrink: 0,
    },
    sourcesList: {
      alignSelf: "flex-start",
      maxWidth: "80%",
      display: "flex",
      flexDirection: "column",
      gap: 3,
      marginTop: 4,
      padding: "8px 10px",
      background: palette.surface,
      border: `1px solid ${palette.borderMuted}`,
      borderRadius: 10,
    },
    sourcesLabel: {
      fontSize: 10.5,
      fontWeight: 600,
      color: palette.textMuted,
      textTransform: "uppercase",
      letterSpacing: "0.04em",
      marginBottom: 2,
    },
    sourceLink: {
      fontSize: 12,
      color: palette.accent,
      textDecoration: "none",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    attachError: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      fontSize: 12.5,
      color: palette.errorText,
      marginBottom: 6,
    },
    editTextarea: {
      width: "100%",
      background: "transparent",
      border: "none",
      color: palette.userText,
      fontSize: 14.5,
      fontFamily: "'Inter', sans-serif",
      resize: "none",
      padding: "11px 15px",
    },
    editActionsRow: {
      display: "flex",
      justifyContent: "flex-end",
      gap: 8,
      padding: "0 10px 8px",
    },
    editCancelButton: {
      background: "transparent",
      border: "none",
      color: palette.userText,
      opacity: 0.75,
      fontSize: 12.5,
      cursor: "pointer",
      padding: "4px 6px",
    },
    editSaveButton: {
      background: "rgba(0,0,0,0.15)",
      border: "none",
      color: palette.userText,
      fontSize: 12.5,
      fontWeight: 600,
      borderRadius: 6,
      cursor: "pointer",
      padding: "4px 10px",
    },
    textarea: {
      flex: 1,
      background: "transparent",
      border: "none",
      color: palette.text,
      fontSize: 14.5,
      fontFamily: "'Inter', sans-serif",
      resize: "none",
      padding: "6px 0",
      maxHeight: 120,
      overflowY: "auto",
    },
    sendButton: {
      background: palette.accent,
      border: "none",
      borderRadius: 10,
      width: 34,
      height: 34,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      cursor: "pointer",
      flexShrink: 0,
    },
    overlay: {
      position: "fixed",
      inset: 0,
      background: palette.overlay,
      zIndex: 10,
    },
    panel: {
      position: "fixed",
      top: 0,
      right: 0,
      height: "100%",
      width: "min(320px, 85vw)",
      background: palette.bg,
      borderLeft: `1px solid ${palette.border}`,
      zIndex: 11,
      padding: "20px",
      display: "flex",
      flexDirection: "column",
      gap: 24,
      animation: "panel-slide-in 0.2s ease-out",
      overflowY: "auto",
    },
    authModal: {
      position: "fixed",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
      width: "min(360px, 88vw)",
      background: palette.bg,
      border: `1px solid ${palette.border}`,
      borderRadius: 16,
      zIndex: 21,
      padding: "20px",
      display: "flex",
      flexDirection: "column",
      gap: 16,
      maxHeight: "85vh",
      overflowY: "auto",
    },
    authNotice: {
      background: palette.surface,
      border: `1px solid ${palette.borderMuted}`,
      borderRadius: 8,
      padding: "8px 10px",
      fontSize: 12.5,
      color: palette.text,
    },
    authErrorText: {
      fontSize: 12.5,
      color: palette.errorText,
    },
    authSwitchLink: {
      background: "transparent",
      border: "none",
      color: palette.accent,
      fontSize: 12.5,
      cursor: "pointer",
      textAlign: "center",
      padding: "2px 0",
    },
    sidebar: {
      position: "fixed",
      top: 0,
      left: 0,
      height: "100%",
      width: "min(300px, 85vw)",
      background: palette.bg,
      borderRight: `1px solid ${palette.border}`,
      zIndex: 11,
      padding: "20px 16px",
      display: "flex",
      flexDirection: "column",
      gap: 14,
      animation: "sidebar-slide-in 0.2s ease-out",
      overflowY: "auto",
    },
    newChatButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
      background: palette.accent,
      color: palette.accentText,
      border: "none",
      borderRadius: 10,
      padding: "9px 0",
      fontSize: 13.5,
      fontWeight: 600,
      cursor: "pointer",
      flexShrink: 0,
    },
    searchWrap: {
      display: "flex",
      alignItems: "center",
      gap: 8,
      background: palette.surface,
      border: `1px solid ${palette.borderMuted}`,
      borderRadius: 10,
      padding: "7px 10px",
      flexShrink: 0,
    },
    searchInput: {
      flex: 1,
      background: "transparent",
      border: "none",
      color: palette.text,
      fontSize: 13,
      fontFamily: "'Inter', sans-serif",
      minWidth: 0,
    },
    conversationList: {
      display: "flex",
      flexDirection: "column",
      gap: 2,
      overflowY: "auto",
    },
    conversationItem: {
      display: "flex",
      alignItems: "center",
      borderRadius: 8,
    },
    conversationItemActive: {
      background: palette.surface,
    },
    conversationItemButton: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      gap: 8,
      background: "transparent",
      border: "none",
      color: palette.text,
      fontSize: 13.5,
      textAlign: "left",
      padding: "9px 8px",
      cursor: "pointer",
      minWidth: 0,
    },
    conversationItemLabel: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    renameInput: {
      flex: 1,
      background: palette.surface,
      border: `1px solid ${palette.accent}`,
      borderRadius: 6,
      color: palette.text,
      fontSize: 13.5,
      fontFamily: "'Inter', sans-serif",
      padding: "8px 8px",
      margin: "0 4px",
      minWidth: 0,
    },
    conversationActions: {
      display: "flex",
      gap: 2,
      flexShrink: 0,
      opacity: 0,
      transition: "opacity 0.15s",
    },
    conversationIconButton: {
      background: "transparent",
      border: "none",
      cursor: "pointer",
      padding: "6px 6px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    panelHeader: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },
    panelTitle: {
      fontFamily: "'Space Grotesk', sans-serif",
      fontWeight: 700,
      fontSize: 17,
    },
    panelSection: {
      display: "flex",
      flexDirection: "column",
      gap: 8,
    },
    panelLabel: {
      fontSize: 12,
      color: palette.textMuted,
      textTransform: "uppercase",
      letterSpacing: "0.05em",
      fontWeight: 600,
    },
    themeToggle: {
      display: "flex",
      gap: 8,
    },
    themeOption: {
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      padding: "9px 0",
      borderRadius: 10,
      border: `1px solid ${palette.borderMuted}`,
      background: "transparent",
      color: palette.textMuted,
      fontSize: 13.5,
      cursor: "pointer",
    },
    themeOptionActive: {
      borderColor: palette.accent,
      color: palette.text,
      background: palette.surface,
    },
    toggleRow: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      background: "transparent",
      border: `1px solid ${palette.borderMuted}`,
      borderRadius: 10,
      padding: "10px 12px",
      color: palette.text,
      fontSize: 13.5,
      cursor: "pointer",
      textAlign: "left",
    },
    toggleRowActive: {
      borderColor: palette.accent,
    },
    toggleSwitch: {
      width: 34,
      height: 20,
      borderRadius: 10,
      background: palette.borderMuted,
      position: "relative",
      flexShrink: 0,
      transition: "background 0.15s",
    },
    toggleSwitchOn: {
      background: palette.accent,
    },
    toggleKnob: {
      position: "absolute",
      top: 2,
      left: 2,
      width: 16,
      height: 16,
      borderRadius: "50%",
      background: palette.bg,
      transition: "transform 0.15s",
    },
    toggleKnobOn: {
      transform: "translateX(14px)",
    },
    textInput: {
      background: palette.surface,
      border: `1px solid ${palette.borderMuted}`,
      borderRadius: 10,
      padding: "9px 12px",
      color: palette.text,
      fontSize: 14,
      fontFamily: "'Inter', sans-serif",
    },
    dangerButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
      background: "transparent",
      border: `1px solid ${palette.errorText}`,
      color: palette.errorText,
      borderRadius: 10,
      padding: "9px 0",
      fontSize: 13.5,
      cursor: "pointer",
      width: "100%",
    },
    secondaryButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
      background: "transparent",
      border: `1px solid ${palette.borderMuted}`,
      color: palette.text,
      borderRadius: 10,
      padding: "9px 0",
      fontSize: 13.5,
      cursor: "pointer",
      width: "100%",
    },
  };
}
